spring:
  application:
    name: heyChatApi
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  servlet:
    context-path: /hey-chat/api